version: "3.9"

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - DEBUG=1
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
